"use client";

import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import LoadingSpinner from "./LoadingSpinner";

const getLeftInfo = (language: string) => {
  if (language === "en") {
    return [
      {
        title: "What is an AI-Audit?",
        desc: "Get a personalized, actionable one-pager and onboarding course outlines for your company, generated by AI based on your website analysis."
      },
      {
        title: "What you get:",
        desc: "• Executive summary of your onboarding challenges\n• AI-generated onboarding course outlines for each key position\n• Concrete recommendations for automation and scaling\n• All results grouped in a single folder for easy access."
      },
      {
        title: "How it works:",
        desc: "1. Enter your company website\n2. Our AI analyzes your website and generates a tailored audit\n3. You receive a ready-to-use onboarding structure and recommendations."
      }
    ];
  } else {
    // Russian (default)
    return [
      {
        title: "Что такое AI-Аудит?",
        desc: "Получите персонализированный, практичный одностраничный документ и планы курсов онбординга для вашей компании, сгенерированные ИИ на основе анализа вашего веб-сайта."
      },
      {
        title: "Что вы получите:",
        desc: "• Исполнительное резюме ваших проблем с онбордингом\n• Сгенерированные ИИ планы курсов онбординга для каждой ключевой позиции\n• Конкретные рекомендации по автоматизации и масштабированию\n• Все результаты сгруппированы в одной папке для легкого доступа."
      },
      {
        title: "Как это работает:",
        desc: "1. Введите адрес веб-сайта вашей компании\n2. Наш ИИ анализирует ваш веб-сайт и генерирует индивидуальный аудит\n3. Вы получаете готовую к использованию структуру онбординга и рекомендации."
      }
    ];
  }
};

const languageOptions = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "ru", label: "Russian" },
  { value: "uk", label: "Ukrainian" },
];

const getLocalizedText = (language: string) => {
  if (language === "en") {
    return {
      title: "AI Audit Generator",
      subtitle: "Enter your company website and let AI analyze it to generate a personalized onboarding audit",
      companyInfo: "Company Information",
      companyWebsite: "Company website",
      companyWebsitePlaceholder: "https://example.com",
      companyWebsiteRequired: "Company website is required",
      language: "Language",
      generateAudit: "Generate AI Audit",
      generatingAudit: "Generating Audit...",
      generateLandingPage: "Generate Dynamic Landing Page",
      generatingLandingPage: "Generating Landing Page...",
      finalizing: "Finalizing...",
      finalizingMessage: "Your AI Audit is being generated. This might take a few minutes.",
      aiPoweredAnalysis: "AI-Powered Analysis",
      aiAnalysisDesc: "Our advanced AI will analyze your responses and generate personalized recommendations.",
      errorGeneration: "Error generating landing page"
    };
  } else {
    // Russian (default)
    return {
      title: "Генератор AI-Аудита",
      subtitle: "Введите адрес веб-сайта вашей компании и позвольте ИИ проанализировать его для создания персонализированного аудита онбординга",
      companyInfo: "Информация о компании",
      companyWebsite: "Веб-сайт компании",
      companyWebsitePlaceholder: "https://example.com",
      companyWebsiteRequired: "Веб-сайт компании обязателен",
      language: "Язык",
      generateAudit: "Сгенерировать AI-Аудит",
      generatingAudit: "Генерация аудита...",
      generateLandingPage: "Сгенерировать динамическую посадочную страницу",
      generatingLandingPage: "Генерация посадочной страницы...",
      finalizing: "Завершение...",
      finalizingMessage: "Ваш AI-Аудит генерируется. Это может занять несколько минут.",
      aiPoweredAnalysis: "Анализ на основе ИИ",
      aiAnalysisDesc: "Наш продвинутый ИИ проанализирует ваши ответы и сгенерирует персонализированные рекомендации.",
      errorGeneration: "Ошибка генерации посадочной страницы"
    };
  }
};

export default function AiAuditQuestionnaire() {
  const [companyWebsite, setCompanyWebsite] = useState("");
  const [selectedLanguage, setSelectedLanguage] = useState("en");
  const [touched, setTouched] = useState<any>({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const router = useRouter();
  const [longLoading, setLongLoading] = useState(false);
  const loadingTimeout = useRef<NodeJS.Timeout | null>(null);
  const [progressMessages, setProgressMessages] = useState<string[]>([]);
  const [jobId, setJobId] = useState<string | null>(null);
  const [generationDone, setGenerationDone] = useState(false);
  const [finalRedirectUrl, setFinalRedirectUrl] = useState<string | null>(null);

  useEffect(() => {
    if (loading) {
      loadingTimeout.current = setTimeout(() => setLongLoading(true), 60000);
    } else {
      setLongLoading(false);
      if (loadingTimeout.current) clearTimeout(loadingTimeout.current);
    }
    return () => {
      if (loadingTimeout.current) clearTimeout(loadingTimeout.current);
    };
  }, [loading]);

  // Polling for progress updates
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (loading && progressMessages.length > 0) {
      interval = setInterval(async () => {
        // Example: fetch progress from backend (replace with real endpoint)
        // const res = await fetch(`/api/custom-projects-backend/ai-audit/progress?jobId=...`);
        // const data = await res.json();
        // setProgressMessages(data.messages);
      }, 2000);
    }
    return () => { if (interval) clearInterval(interval); };
  }, [loading, progressMessages]);

  // Poll for progress and result
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (jobId && loading) {
      console.log(`🔄 [FRONTEND DATA FLOW] Starting progress polling for job ID: ${jobId}`)
      interval = setInterval(async () => {
        try {
          const progressUrl = `/api/custom-projects-backend/ai-audit/progress?jobId=${jobId}`
          console.log(`📡 [FRONTEND DATA FLOW] Polling progress from: ${progressUrl}`)
          
          const res = await fetch(progressUrl);
        const data = await res.json();
          
          // 📊 LOG: Progress data received
          console.log(`📊 [FRONTEND DATA FLOW] Progress data received:`, data)
          
          if (data.messages) {
            console.log(`📊 [FRONTEND DATA FLOW] Progress messages: ${data.messages.length} messages`)
            setProgressMessages(data.messages);
          }
          
        if (data.result && (data.result.folderId || data.result.id)) {
            console.log(`✅ [FRONTEND DATA FLOW] Generation result received:`, data.result)
          setGenerationDone(true);
            
            // Check if this is a landing page generation result
            if (data.result.name && data.result.name.includes("Landing Page")) {
              const redirectUrl = `/create/audit-2-dynamic/${data.result.id}`
              console.log(`🎯 [FRONTEND DATA FLOW] Landing page detected, redirecting to: ${redirectUrl}`)
              setFinalRedirectUrl(redirectUrl);
            } else {
              const redirectUrl = data.result.folderId ? `/projects?folder=${data.result.folderId}` : `/projects/view/${data.result.id}`
              console.log(`🎯 [FRONTEND DATA FLOW] Regular audit detected, redirecting to: ${redirectUrl}`)
              setFinalRedirectUrl(redirectUrl);
            }
          setLoading(false);
          }
        } catch (error) {
          console.error(`❌ [FRONTEND DATA FLOW] Error polling progress:`, error)
        }
      }, 2000);
    }
    return () => { 
      if (interval) {
        console.log(`🛑 [FRONTEND DATA FLOW] Stopping progress polling`)
        clearInterval(interval)
      }
    };
  }, [jobId, loading]);


  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setTouched({
      companyWebsite: true,
    });
    if (!companyWebsite.trim()) return;
    setLoading(true);
    setError("");
    setProgressMessages([]);
    setJobId(null);
    setGenerationDone(false);
    setFinalRedirectUrl(null);
    try {
      const CUSTOM_BACKEND_URL = process.env.NEXT_PUBLIC_CUSTOM_BACKEND_URL || "/api/custom-projects-backend";
      
      // Create minimal payload - backend will scrape website for all other data
      const payload = {
        companyWebsite,
        language: selectedLanguage,
      };
      
      console.log(`📡 [FRONTEND DATA FLOW] Sending minimal payload:`, payload);
      
      const res = await fetch(`${CUSTOM_BACKEND_URL}/ai-audit/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error("Ошибка генерации AI-аудита");
      const data = await res.json();
      if (data.jobId) {
        setJobId(data.jobId);
      } else if (data.folderId || data.id) {
        // fallback: immediate result
        setGenerationDone(true);
        setFinalRedirectUrl(data.folderId ? `/projects?folder=${data.folderId}` : `/projects/view/${data.id}`);
        setLoading(false);
      }
    } catch (err: any) {
      setError(err.message || "Ошибка генерации AI-аудита");
      setLoading(false);
    }
  };

  const handleGenerateLandingPage = async () => {
    // 📊 LOG: Landing page generation started
    console.log(`🚀 [FRONTEND DATA FLOW] Starting landing page generation`)
    
    setTouched({
      companyWebsite: true,
    });
    
    // 📊 LOG: Form validation
    console.log(`📝 [FRONTEND DATA FLOW] Form data to be submitted:`, { companyWebsite, language: selectedLanguage })
    
    if (!companyWebsite.trim()) {
      console.error(`❌ [FRONTEND DATA FLOW] Form validation failed`)
      return;
    }
    
    console.log(`✅ [FRONTEND DATA FLOW] Form validation passed`)
    setLoading(true);
    setError("");
    setProgressMessages([]);
    setJobId(null);
    setGenerationDone(false);
    setFinalRedirectUrl(null);
    
    try {
      const CUSTOM_BACKEND_URL = process.env.NEXT_PUBLIC_CUSTOM_BACKEND_URL || "/api/custom-projects-backend";
      const apiUrl = `${CUSTOM_BACKEND_URL}/ai-audit/landing-page/generate`
      
      // Create minimal payload - backend will scrape website for all other data
      const payload = {
        companyWebsite,
        language: selectedLanguage,
      };
      
      // 📊 LOG: API request details
      console.log(`📡 [FRONTEND DATA FLOW] Making API request to: ${apiUrl}`)
      console.log(`📡 [FRONTEND DATA FLOW] Request payload:`, payload)
      
      const res = await fetch(apiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      
      // 📊 LOG: API response
      console.log(`📡 [FRONTEND DATA FLOW] API response status: ${res.status}`)
      console.log(`📡 [FRONTEND DATA FLOW] API response ok: ${res.ok}`)
      
      if (!res.ok) {
        const errorText = await res.text()
        console.error(`❌ [FRONTEND DATA FLOW] API request failed: ${res.status} - ${errorText}`)
        throw new Error(getLocalizedText(selectedLanguage).errorGeneration);
      }
      const data = await res.json();
      
      // 📊 LOG: API response data
      console.log(`📥 [FRONTEND DATA FLOW] API response data:`, data)
      
      if (data.jobId) {
        console.log(`🔄 [FRONTEND DATA FLOW] Job ID received: ${data.jobId}`)
        setJobId(data.jobId);
      } else if (data.id) {
        // fallback: immediate result
        console.log(`✅ [FRONTEND DATA FLOW] Immediate result received, project ID: ${data.id}`)
        setGenerationDone(true);
        setFinalRedirectUrl(`/create/audit-2-dynamic/${data.id}`);
        setLoading(false);
      }
    } catch (err: any) {
      console.error(`❌ [FRONTEND DATA FLOW] Error in landing page generation:`, err)
      setError(err.message || getLocalizedText(selectedLanguage).errorGeneration);
      setLoading(false);
    }
  };

  // In the render, after loading is false and generationDone is true, redirect
  useEffect(() => {
    if (generationDone && finalRedirectUrl) {
      console.log(`🔄 [FRONTEND DATA FLOW] Generation complete, redirecting to: ${finalRedirectUrl}`)
      setTimeout(() => {
        console.log(`🚀 [FRONTEND DATA FLOW] Executing redirect to: ${finalRedirectUrl}`)
        router.push(finalRedirectUrl);
      }, 1200);
    }
  }, [generationDone, finalRedirectUrl]);

  // Only show the latest progress message
  const latestProgress = progressMessages.length > 0 ? progressMessages[progressMessages.length - 1] : null;

  // Redirect to /projects when audit is complete
  useEffect(() => {
    if (latestProgress && latestProgress.toLowerCase().includes('ai-audit complete')) {
      setTimeout(() => {
        router.push('/projects');
      }, 800);
    }
  }, [latestProgress, router]);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100 font-sans relative overflow-hidden">
      {/* Background decorative elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-blue-200 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-purple-200 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
        <div className="absolute top-40 left-40 w-80 h-80 bg-pink-200 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
      </div>
      
      <div className="relative z-10 flex flex-col items-center justify-center min-h-screen p-4">
        <div className="w-full max-w-6xl flex flex-col lg:flex-row bg-white/80 backdrop-blur-sm rounded-3xl shadow-2xl border border-white/20 overflow-hidden">
          {/* Left info column */}
          <div className="lg:w-2/5 bg-gradient-to-br from-blue-600 via-blue-700 to-indigo-800 px-8 py-12 lg:py-16 flex flex-col relative overflow-hidden">
            {/* Decorative background pattern */}
            <div className="absolute inset-0 opacity-10">
              <div className="absolute top-0 left-0 w-full h-full bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2260%22%20height%3D%2260%22%20viewBox%3D%220%200%2060%2060%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Cg%20fill%3D%22%23ffffff%22%20fill-opacity%3D%220.1%22%3E%3Ccircle%20cx%3D%2230%22%20cy%3D%2230%22%20r%3D%222%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')]"></div>
            </div>
            
            <div className="relative z-10">
              <h2 className="text-3xl font-bold text-white mb-8 flex items-center gap-3">
                <div className="p-2 bg-white/20 rounded-lg">
                  <svg width="32" height="32" fill="none" viewBox="0 0 24 24" className="text-white">
                    <circle cx="12" cy="12" r="10" fill="currentColor" opacity="0.2"/>
                    <path d="M12 8v4l3 2" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </div>
                AI-Audit Overview
              </h2>
              
              {getLeftInfo(selectedLanguage).map((item, idx) => (
                <div key={item.title} className={`${idx !== 0 ? "mt-8" : ""} group`}>
                  <div className="text-xl font-semibold text-white mb-3 group-hover:text-blue-100 transition-colors">
                    {item.title}
                  </div>
                  <div className="text-blue-100 text-base leading-relaxed whitespace-pre-line">
                    {item.desc}
                  </div>
                </div>
              ))}
              
              {/* Progress indicator */}
              <div className="mt-12 p-4 bg-white/10 rounded-xl border border-white/20">
                <div className="flex items-center gap-3 text-white">
                  <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
                  <span className="text-sm font-medium">{getLocalizedText(selectedLanguage).aiPoweredAnalysis}</span>
                </div>
                <p className="text-blue-100 text-sm mt-2">
                  {getLocalizedText(selectedLanguage).aiAnalysisDesc}
                </p>
              </div>
            </div>
          </div>
          
          {/* Right form column */}
          <div className="lg:w-3/5 p-8 lg:p-12 flex flex-col justify-center bg-white/90 backdrop-blur-sm">
            <div className="max-w-2xl mx-auto w-full">
              <div className="text-center mb-8">
                <h1 className="text-4xl font-bold mb-3 bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                  {getLocalizedText(selectedLanguage).title}
                </h1>
                <p className="text-gray-600 text-lg">
                  {getLocalizedText(selectedLanguage).subtitle}
                </p>
              </div>
              
              {progressMessages.length > 0 && (
                <div className="mb-6 p-4 bg-blue-50 rounded-xl border border-blue-200">
                  {progressMessages.map((msg, i) => (
                    <div key={i} className="text-blue-700 text-sm mb-1 flex items-center gap-2">
                      <div className="w-1.5 h-1.5 bg-blue-500 rounded-full"></div>
                      {msg}
                    </div>
                  ))}
                </div>
              )}
              
              {loading && <LoadingSpinner text={latestProgress || "Generating..."} />}
              
              {!loading && (
                <form onSubmit={handleSubmit} className="space-y-8">
                  {/* Company Website Section */}
                  <div className="space-y-6">
                    <h3 className="text-xl font-semibold text-gray-800 border-b border-gray-200 pb-2">
                      {getLocalizedText(selectedLanguage).companyInfo}
                    </h3>
                    
                    <div>
                      <label className="block font-semibold mb-2 text-gray-700">{getLocalizedText(selectedLanguage).companyWebsite}</label>
                      <input
                        type="url"
                        className={`w-full px-4 py-3 rounded-xl border-2 transition-all duration-200 ${
                          touched.companyWebsite && !companyWebsite.trim() 
                            ? 'border-red-400 bg-red-50' 
                            : 'border-gray-200 bg-white hover:border-blue-300 focus:border-blue-500 focus:bg-blue-50'
                        } focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-gray-800 placeholder-gray-400`}
                        value={companyWebsite}
                        onChange={e => setCompanyWebsite(e.target.value)}
                        onBlur={() => setTouched((t:any) => ({ ...t, companyWebsite: true }))}
                        placeholder={getLocalizedText(selectedLanguage).companyWebsitePlaceholder}
                        required
                      />
                      {touched.companyWebsite && !companyWebsite.trim() && (
                        <div className="text-red-500 text-sm mt-1 flex items-center gap-1">
                          <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                          </svg>
                          {getLocalizedText(selectedLanguage).companyWebsiteRequired}
                        </div>
                      )}
                    </div>
                    
                    <div>
                      <label className="block font-semibold mb-2 text-gray-700">{getLocalizedText(selectedLanguage).language}</label>
                      <select
                        className="w-full px-4 py-3 rounded-xl border-2 border-gray-200 bg-white hover:border-blue-300 focus:border-blue-500 focus:bg-blue-50 focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-gray-800"
                        value={selectedLanguage}
                        onChange={e => setSelectedLanguage(e.target.value)}
                      >
                        {languageOptions.map(option => (
                          <option key={option.value} value={option.value} className="text-gray-800">
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                  
                  {/* Submit Buttons */}
                  <div className="pt-6 space-y-4">
                    <button
                      type="submit"
                      className="w-full px-8 py-4 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white text-xl font-bold shadow-lg hover:shadow-xl transition-all duration-200 transform hover:scale-[1.02] disabled:opacity-60 disabled:cursor-not-allowed disabled:transform-none"
                      disabled={loading}
                    >
                      {loading ? (
                        <div className="flex items-center justify-center gap-3">
                          <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                          {getLocalizedText(selectedLanguage).generatingAudit}
                        </div>
                      ) : (
                        <div className="flex items-center justify-center gap-3">
                          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                          </svg>
                          {getLocalizedText(selectedLanguage).generateAudit}
                        </div>
                      )}
                    </button>
                    
                    <button
                      type="button"
                      onClick={handleGenerateLandingPage}
                      className="w-full px-8 py-4 rounded-xl bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white text-lg font-semibold shadow-lg hover:shadow-xl transition-all duration-200 transform hover:scale-[1.02] disabled:opacity-60 disabled:cursor-not-allowed disabled:transform-none"
                      disabled={loading}
                    >
                      {loading ? (
                        <div className="flex items-center justify-center gap-3">
                          <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                          {getLocalizedText(selectedLanguage).generatingLandingPage}
                        </div>
                      ) : (
                        <div className="flex items-center justify-center gap-3">
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                          </svg>
                          {getLocalizedText(selectedLanguage).generateLandingPage}
                        </div>
                      )}
                    </button>
                    
                    {error && (
                      <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl text-red-600 text-center">
                        <div className="flex items-center justify-center gap-2">
                          <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                          </svg>
                          {error}
                        </div>
                      </div>
                    )}
                  </div>
                </form>
              )}
              
              {generationDone && (
                <div className="mt-8 text-center p-6 bg-green-50 border border-green-200 rounded-xl">
                  <LoadingSpinner text={getLocalizedText(selectedLanguage).finalizing} />
                  <p className="text-green-700 text-sm mt-3">
                    {getLocalizedText(selectedLanguage).finalizingMessage}
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      
      {/* Custom CSS for animations */}
      <style jsx>{`
        @keyframes blob {
          0% {
            transform: translate(0px, 0px) scale(1);
          }
          33% {
            transform: translate(30px, -50px) scale(1.1);
          }
          66% {
            transform: translate(-20px, 20px) scale(0.9);
          }
          100% {
            transform: translate(0px, 0px) scale(1);
          }
        }
        .animate-blob {
          animation: blob 7s infinite;
        }
        .animation-delay-2000 {
          animation-delay: 2s;
        }
        .animation-delay-4000 {
          animation-delay: 4s;
        }
      `}</style>
    </main>
  );
} 