export type ValidSources = string;

export type CredentialTemplate = Record<string, any> | null | {
  authentication_method: string;
  authMethods: Array<{
    value: string;
    label: string;
    fields: Record<string, any>;
  }>;
};

export const credentialTemplates: Record<ValidSources, CredentialTemplate> = {
  github: { github_access_token: "" },
  gitlab: { gitlab_url: "", gitlab_access_token: "" },
  slack: { slack_bot_token: "" },
  bookstack: { bookstack_base_url: "", bookstack_api_token_id: "", bookstack_api_token_secret: "" },
  confluence: { confluence_username: "", confluence_access_token: "" },
  jira: { jira_user_email: null, jira_api_token: "" },
  productboard: { productboard_access_token: "" },
  slab: { slab_bot_token: "" },
  notion: { notion_integration_token: "" },
  guru: { guru_user: "", guru_user_token: "" },
  gong: { gong_access_key: "", gong_access_key_secret: "" },
  zulip: { zuliprc_content: "" },
  linear: { linear_access_token: "" },
  hubspot: { hubspot_access_token: "" },
  document360: { portal_id: "", document360_api_token: "" },
  loopio: { loopio_subdomain: "", loopio_client_id: "", loopio_client_token: "" },
  dropbox: { dropbox_access_token: "" },
  salesforce: { sf_username: "", sf_password: "", sf_security_token: "", is_sandbox: false },
  sharepoint: { sp_client_id: "", sp_client_secret: "", sp_directory_id: "" },
  asana: { asana_api_token_secret: "" },
  teams: { teams_client_id: "", teams_client_secret: "", teams_directory_id: "" },
  zendesk: { zendesk_subdomain: "", zendesk_email: "", zendesk_token: "" },
  discourse: { discourse_api_key: "", discourse_api_username: "" },
  axero: { base_url: "", axero_api_token: "" },
  clickup: { clickup_api_token: "", clickup_team_id: "" },
  s3: {
    authentication_method: "access_key",
    authMethods: [
      { value: "access_key", label: "Access Key and Secret", fields: { aws_access_key_id: "", aws_secret_access_key: "" } },
      { value: "iam_role", label: "IAM Role", fields: { aws_role_arn: "" } },
    ],
  },
  r2: { account_id: "", r2_access_key_id: "", r2_secret_access_key: "" },
  google_cloud_storage: { access_key_id: "", secret_access_key: "" },
  oci_storage: { namespace: "", region: "", access_key_id: "", secret_access_key: "" },
  freshdesk: { freshdesk_domain: "", freshdesk_password: "", freshdesk_api_key: "" },
  fireflies: { fireflies_api_key: "" },
  egnyte: { domain: "", access_token: "" },
  airtable: { airtable_access_token: "" },
  discord: { discord_bot_token: "" },
  gitbook: { gitbook_api_key: "" },
  google_drive: { google_service_account_key: "", google_primary_admin: "" },
  gmail: { google_service_account_key: "", google_primary_admin: "" },
  xenforo: null,
  google_sites: null,
  file: null,
  wikipedia: null,
  mediawiki: null,
  web: null,
  not_applicable: null,
  ingestion_api: null,
};

export const credentialDisplayNames: Record<string, string> = {
  github_access_token: "GitHub Access Token",
  gitlab_url: "GitLab URL",
  gitlab_access_token: "GitLab Access Token",
  bookstack_base_url: "Bookstack Base URL",
  bookstack_api_token_id: "Bookstack API Token ID",
  bookstack_api_token_secret: "Bookstack API Token Secret",
  confluence_username: "Confluence Username",
  confluence_access_token: "Confluence Access Token",
  jira_user_email: "Jira User Email (required for Jira Cloud)",
  jira_api_token: "API or Personal Access Token",
  productboard_access_token: "Productboard Access Token",
  slack_bot_token: "Slack Bot Token",
  discord_bot_token: "Discord Bot Token",
  google_tokens: "Google OAuth Tokens",
  google_service_account_key: "Google Service Account JSON",
  google_primary_admin: "Primary Admin Email",
  slab_bot_token: "Slab Bot Token",
  notion_integration_token: "Notion Integration Token",
  zuliprc_content: "Zuliprc Content",
  guru_user: "Guru User",
  guru_user_token: "Guru User Token",
  gong_access_key: "Gong Access Key",
  gong_access_key_secret: "Gong Access Key Secret",
  loopio_subdomain: "Loopio Subdomain",
  loopio_client_id: "Loopio Client ID",
  loopio_client_token: "Loopio Client Token",
  linear_access_token: "Linear Access Token",
  hubspot_access_token: "HubSpot Access Token",
  portal_id: "Document360 Portal ID",
  document360_api_token: "Document360 API Token",
  clickup_api_token: "ClickUp API Token",
  clickup_team_id: "ClickUp Team ID",
  zendesk_subdomain: "Zendesk Subdomain",
  zendesk_email: "Zendesk Email",
  zendesk_token: "Zendesk Token",
  dropbox_access_token: "Dropbox API Key",
  account_id: "R2 Account ID",
  r2_access_key_id: "R2 Access Key ID",
  r2_secret_access_key: "R2 Secret Access Key",
  aws_access_key_id: "AWS Access Key ID",
  aws_secret_access_key: "AWS Secret Access Key",
  aws_role_arn: "AWS Role ARN",
  authentication_method: "Authentication Method",
  access_key_id: "GCS Access Key ID",
  secret_access_key: "GCS Secret Access Key",
  namespace: "OCI Namespace",
  region: "OCI Region",
  sf_username: "Salesforce Username",
  sf_password: "Salesforce Password",
  sf_security_token: "Salesforce Security Token",
  is_sandbox: "Is Sandbox Environment",
  sp_client_id: "SharePoint Client ID",
  sp_client_secret: "SharePoint Client Secret",
  sp_directory_id: "SharePoint Directory ID",
  asana_api_token_secret: "Asana API Token",
  teams_client_id: "Microsoft Teams Client ID",
  teams_client_secret: "Microsoft Teams Client Secret",
  teams_directory_id: "Microsoft Teams Directory ID",
  discourse_api_key: "Discourse API Key",
  discourse_api_username: "Discourse API Username",
  base_url: "Axero Base URL",
  axero_api_token: "Axero API Token",
  freshdesk_domain: "Freshdesk Domain",
  freshdesk_password: "Freshdesk Password",
  freshdesk_api_key: "Freshdesk API Key",
  fireflies_api_key: "Fireflies API Key",
  domain: "Egnyte Domain",
  access_token: "Egnyte Access Token",
  airtable_access_token: "Airtable Access Token",
  gitbook_api_key: "GitBook API Key",
}; 